name: env_py310
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2024.3.11=h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - lame=3.100=h7b6447c_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.4=h5eee18b_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libvpx=1.7.0=h439df22_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.14=h5eee18b_0
  - pip=23.3.1=py310h06a4308_0
  - python=3.10.13=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py310h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py310h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.5=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.0.0
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.2.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-lru==2.0.4
      - async-timeout==4.0.3
      - attrs==23.2.0
      - audioread==3.0.1
      - babel==2.15.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - braceexpand==0.1.7
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - comm==0.2.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - cython==3.0.10
      - cytoolz==0.12.3
      - datasets==2.16.1
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dill==0.3.7
      - distance==0.1.3
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - editdistance==0.8.1
      - entmax==1.3
      - evaluate==0.4.1
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastjsonschema==2.20.0
      - ffmpeg==1.4
      - filelock==3.13.1
      - fonttools==4.53.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - future==1.0.0
      - g2p-en==2.1.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - grpcio==1.64.1
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.20.1
      - hydra-core==1.3.2
      - idna==3.6
      - inflect==7.2.1
      - intervaltree==3.1.0
      - ipykernel==6.29.4
      - ipython==8.25.0
      - ipywidgets==8.1.3
      - isoduration==20.11.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - jiwer==3.0.4
      - joblib==1.3.2
      - json5==0.9.25
      - jsonargparse==3.13.1
      - jsonpointer==3.0.0
      - jsonschema==4.22.0
      - jsonschema-specifications==2023.12.1
      - jupyter==1.0.0
      - jupyter-client==8.6.2
      - jupyter-console==6.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.10.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.14.1
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.2.2
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.2
      - jupyterlab-widgets==3.0.11
      - kaldi-python-io==1.2.2
      - kaldiio==2.18.0
      - kiwisolver==1.4.5
      - langdetect==1.0.9
      - lazy-loader==0.4
      - levenshtein==0.25.1
      - lhotse==1.24.1
      - librosa==0.10.2.post1
      - lightning-utilities==0.11.2
      - lilcom==1.7
      - llvmlite==0.43.0
      - loguru==0.7.2
      - lxml==5.2.2
      - markdown==3.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - marshmallow==3.21.3
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.0.2
      - more-itertools==10.3.0
      - mpmath==1.3.0
      - msgpack==1.0.8
      - multidict==6.0.4
      - multiprocess==0.70.15
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nemo-toolkit==1.23.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nltk==3.8.1
      - notebook==7.2.1
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - onnx==1.16.1
      - openai==1.6.1
      - openai-whisper==20231117
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.1.4
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.3.0
      - plac==1.4.3
      - platformdirs==4.2.2
      - pooch==1.8.2
      - portalocker==2.8.2
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.47
      - protobuf==4.25.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyannote-core==5.0.0
      - pyannote-database==5.1.0
      - pyannote-metrics==3.2.1
      - pyarrow==14.0.2
      - pyarrow-hotfix==0.6
      - pybind11==2.12.0
      - pycparser==2.22
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pydub==0.25.1
      - pygments==2.18.0
      - pyloudnorm==0.1.1
      - pyparsing==3.1.2
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-json-logger==2.0.7
      - pytorch-lightning==2.0.7
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - qtconsole==5.5.2
      - qtpy==2.4.1
      - rapidfuzz==3.9.3
      - referencing==0.35.1
      - regex==2023.12.25
      - requests==2.31.0
      - resampy==0.4.3
      - responses==0.18.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rouge-score==0.1.2
      - rpds-py==0.18.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - sacrebleu==2.4.2
      - sacremoses==0.1.1
      - safetensors==0.4.1
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sentencepiece==0.1.99
      - sentry-sdk==2.6.0
      - setproctitle==1.3.3
      - shellingham==1.5.4
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - soundfile==0.12.1
      - soupsieve==2.5
      - sox==1.5.0
      - soxr==0.3.7
      - stack-data==0.6.3
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.17.0
      - tensorboard-data-server==0.7.2
      - termcolor==2.4.0
      - terminado==0.18.1
      - text-unidecode==1.3
      - texterrors==0.5.1
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - tinycss2==1.3.0
      - tokenizers==0.15.0
      - tomli==2.0.1
      - toolz==0.12.1
      - torch==2.3.1
      - torchaudio==2.3.1
      - torchmetrics==0.10.3
      - tornado==6.4.1
      - tqdm==4.66.1
      - traitlets==5.14.3
      - transformers==4.36.2
      - triton==2.3.1
      - typeguard==4.3.0
      - typer==0.12.3
      - types-python-dateutil==2.9.0.20240316
      - typing-extensions==4.12.2
      - tzdata==2023.4
      - unbabel-comet==2.2.2
      - uri-template==1.3.0
      - urllib3==2.1.0
      - wandb==0.17.2
      - wcwidth==0.2.13
      - webcolors==24.6.0
      - webdataset==0.1.62
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.0.3
      - wget==3.2
      - whisper==1.1.10
      - widgetsnbextension==4.0.11
      - wrapt==1.16.0
      - xxhash==3.4.1
      - yarl==1.9.4
      - youtokentome==1.0.6
